### ISSUE TITLE
Error submitting forecast for FluSight 2017-18

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#6]
I tried to upload the historical average forecast for the first submission deadline and received an "Unable to parse CSV" error: 
![image](https://user-images.githubusercontent.com/20864042/32336399-9e6b9826-bfc5-11e7-870e-f46466bf7e58.png)

I've emailed you the submission file as well as the template I used to set up the submissions on the admin side since GitHub doesn't support CSVs.

**Comment by craigjmcgowan** [comment]
To follow up, I get the same error when trying to upload a forecast for the state FluSight challenge

**Comment by cdc-mgz4** [comment]
Please try to upload your submission again, this should be solved.

**Comment by craigjmcgowan** [comment]
This appears to have worked for the national forecasts. It uploaded successfully and came through in the JSON file.

I'm still having issues with the state file. I received error messages for what appears to be all location/target combinations when I uploaded the file I sent you earlier.

**Comment by cdc-mgz4** [comment]
Please send me the state file you are uploading, I'm only finding the Hist-Avg forecast. It might be good to meet for 30 min to get this sorted out ASAP.

**Comment by cdc-mgz4** [comment]
A fix for state level forecast should be up.

**Comment by craigjmcgowan** [comment]
I think we're getting close! I retried and the submission mostly was accepted. However, I got errors for all targets for the following states: Iowa, Ohio, Utah. The error was "Invalid location
No matching target, location pair for this project.". Looking at the locations listed in the submission field, none of those states are there. However, they are all in the template file I uploaded to create the submission (same one I sent you yesterday). Is there something off in how I set up those states in the template?

**Comment by cdc-mgz4** [comment]
Delete and re-upload the template with your admin account.

**Comment by craigjmcgowan** [comment]
I'm still not seeing those states show up in the locations. When I inspect the network traffic I'm getting a 500 error:
![image](https://user-images.githubusercontent.com/20864042/32553306-84540fb0-c464-11e7-9b41-bafb3bc814c0.png)

**Comment by cdc-mgz4** [comment]
I forgot to restart the server for these changes, my bad. It should work. I tested this with your template and submission file. If it still doesn't after this I will have a closer look.

**Comment by craigjmcgowan** [comment]
That seems to have done it! I'll edit the due date and let teams know they can attempt to resubmit. Thanks!
